# Character マスタ初回作成（画像は URL のみ。クイズは active+full_body）。
# Generated by Django 6.0.8 on 2026-09-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#4cc9f0', max_length=32)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('api_image_url', models.URLField(blank=True, max_length=500)),
                ('image_kind', models.CharField(choices=[('full_body', 'Full body'), ('portrait', 'Portrait'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('brawlapi', 'BrawlAPI'), ('manual', 'Manual'), ('extra', 'Extra')], default='brawlapi', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'ordering': ['name_en'],
            },
        ),
    ]
